const util = require('./src/util.js');

exports.Client = class {
  constructor(){
    this.honorifics = util.honorifics,
    this.searchAnime = util.searchAnime,
    this.searchManga = util.searchManga,
    this.searchHonorific = util.honoFunction,
    this.nameHonorific = util.nameHonorific,
    this.meme = util.meme,
    this.nsfw = {
      anal: util.nekoNsfw('anal'),
      avatar: util.nekoNsfw('avatar'),
      bj: util.nekoNsfw('bJ'),
      blowJob: util.nekoNsfw('blowJob'),
      boobs: util.nekoNsfw('boobs'),
      classic: util.nekoNsfw('classic'),
      cumArts:  util.nekoNsfw('cumArts'),
      cumsluts: util.nekoNsfw('cumsluts'),
      ero: util.nekoNsfw('ero'),
      eroFeet: util.nekoNsfw('eroFeet'),
      eroKemonomimi: util.nekoNsfw('eroKemonomimi'),
      eroKitsune: util.nekoNsfw('eroKitsune'),
      eroNeko: util.nekoNsfw('eroNeko'),
      eroYuri: util.nekoNsfw('eroYuri'),
      feet: util.nekoNsfw('feet'),
      feetGif: util.nekoNsfw('feetGif'),
      femdom: util.nekoNsfw('femdom'),
      futanari: util.nekoNsfw('futanari'),
      gasm: util.nekoNsfw('gasm'),
      girlSolo: util.nekoNsfw('girlSolo'),
      girlSoloGif: util.nekoNsfw('girlSoloGif'),
      hentai: util.nekoNsfw('hentai'),
      holo: util.nekoNsfw('holo'),
      holoEro: util.nekoNsfw('holoEro'),
      kemonomimi: util.nekoNsfw('kemonomimi'),
      keta: util.nekoNsfw('keta'),
      kitsune: util.nekoNsfw('kitsune'),
      kuni: util.nekoNsfw('kuni'),
      lesbian: util.nekoNsfw('lesbian'),
      neko: util.nekoNsfw('neko'),
      nekoGif: util.nekoNsfw('nekoGif'),
      pussy: util.nekoNsfw('pussy'),
      pussyArt: util.nekoNsfw('pussyArt'),
      pussyWankGif: util.nekoNsfw('pussyWankGif'),
      randomHentaiGif: util.nekoNsfw('randomHentaiGif'),
      spank: util.nekoNsfw('spank'),
      tits: util.nekoNsfw('tits'),
      trap: util.nekoNsfw('trap'),
      yuri: util.nekoNsfw('yuri')
    },
    this.sfw = {
      avatar: util.nekoSfw('avatar'),
      baka: util.nekoSfw('baka'),
      Ball8: util.nekoSfw('Ball8'),
      catText: util.nekoSfw('catText'),
      cuddle: util.nekoSfw('cuddle'),
      fact: util.nekoSfw('fact'),
      feed: util.nekoSfw('feed'),
      foxGirl: util.nekoSfw('foxGirl'),
      gecg: util.nekoSfw('gecg'),
      goose: util.nekoSfw('goose'),
      holo: util.nekoSfw('holo'),
      hug: util.nekoSfw('hug'),
      kemonomimi: util.nekoSfw('kemonomimi'),
      kiss: util.nekoSfw('kiss'),
      lizard: util.nekoSfw('lizard'),
      meow: util.nekoSfw('meow'),
      neko: util.nekoSfw('neko'),
      nekoGif: util.nekoSfw('nekoGif'),
      OwOify: util.nekoSfw('OwOify'),
      pat: util.nekoSfw('pat'),
      poke: util.nekoSfw('poke'),
      slap: util.nekoSfw('slap'),
      smug: util.nekoSfw('smug'),
      spoiler: util.nekoSfw('spoiler'),
      tickle: util.nekoSfw('tickle'),
      waifu: util.nekoSfw('waifu'),
      why: util.nekoSfw('why'),
      woof: util.nekoSfw('woof')
    }
    this.nekoWallpaper = util.nekoWallpaper
  }
}
        