const util = require('./src/util.js');

exports.Client = class {
  constructor(){
    this.searchAnime = util.searchAnime,
    this.searchManga = util.searchManga,
    this.searchHonorific = util.honoFunction,
    this.nameHonorific = util.nameHonorific,
    this.meme = util.meme,
    //this.honorifics = util.honorifics,
    this.nekoNsfw = {
      anal: util.nekoNsfw('anal'),
      avatar: util.nekoNsfw('avatar'),
      bj: util.nekoNsfw('bJ'),
      blowJob: util.nekoNsfw('blowJob'),
      boobs: util.nekoNsfw('boobs'),
      classic: util.nekoNsfw('classic'),
      cumArts:  util.nekoNsfw('cumArts'),
      cumsluts: util.nekoNsfw('cumsluts'),
      ero: util.nekoNsfw('ero'),
      eroFeet: util.nekoNsfw('eroFeet'),
      eroKemonomimi: util.nekoNsfw('eroKemonomimi'),
      eroKitsune: util.nekoNsfw('eroKitsune'),
      eroNeko: util.nekoNsfw('eroNeko'),
      eroYuri: util.nekoNsfw('eroYuri'),
      feet: util.nekoNsfw('feet'),
      feetGif: util.nekoNsfw('feetGif'),
      femdom: util.nekoNsfw('femdom'),
      futanari: util.nekoNsfw('futanari'),
      gasm: util.nekoNsfw('gasm'),
      girlSolo: util.nekoNsfw('girlSolo'),
      girlSoloGif: util.nekoNsfw('girlSoloGif'),
      hentai: util.nekoNsfw('hentai'),
      holo: util.nekoNsfw('holo'),
      holoEro: util.nekoNsfw('holoEro'),
      kemonomimi: util.nekoNsfw('kemonomimi'),
      keta: util.nekoNsfw('keta'),
      kitsune: util.nekoNsfw('kitsune'),
      kuni: util.nekoNsfw('kuni'),
      lesbian: util.nekoNsfw('lesbian'),
      neko: util.nekoNsfw('neko'),
      nekoGif: util.nekoNsfw('nekoGif'),
      pussy: util.nekoNsfw('pussy'),
      pussyArt: util.nekoNsfw('pussyArt'),
      pussyWankGif: util.nekoNsfw('pussyWankGif'),
      randomHentaiGif: util.nekoNsfw('randomHentaiGif'),
      spank: util.nekoNsfw('spank'),
      tits: util.nekoNsfw('tits'),
      trap: util.nekoNsfw('trap'),
      yuri: util.nekoNsfw('yuri')
    },
    this.nekoWallpaper = util.nekoWallpaper
  }
}
                